/* Generated by wayland-scanner 1.25.0 */

#ifndef HYPRLAND_CTM_CONTROL_V1_CLIENT_PROTOCOL_H
#define HYPRLAND_CTM_CONTROL_V1_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_hyprland_ctm_control_v1 The hyprland_ctm_control_v1 protocol
 * controlling outputs' color transform matrix
 *
 * @section page_desc_hyprland_ctm_control_v1 Description
 *
 * This protocol allows a client to control outputs' color transform matrix (CTM).
 *
 * This protocol is privileged and should not be exposed to unprivileged clients.
 *
 * @section page_ifaces_hyprland_ctm_control_v1 Interfaces
 * - @subpage page_iface_hyprland_ctm_control_manager_v1 - manager to control CTMs
 * @section page_copyright_hyprland_ctm_control_v1 Copyright
 * <pre>
 *
 * Copyright © 2024 Vaxry
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * </pre>
 */
struct hyprland_ctm_control_manager_v1;
struct wl_output;

#ifndef HYPRLAND_CTM_CONTROL_MANAGER_V1_INTERFACE
#define HYPRLAND_CTM_CONTROL_MANAGER_V1_INTERFACE
/**
 * @page page_iface_hyprland_ctm_control_manager_v1 hyprland_ctm_control_manager_v1
 * @section page_iface_hyprland_ctm_control_manager_v1_desc Description
 *
 * This object is a manager which offers requests to control CTMs.
 *
 * If any changes are done, once this object is destroyed, CTMs are reset back to
 * an identity matrix.
 * @section page_iface_hyprland_ctm_control_manager_v1_api API
 * See @ref iface_hyprland_ctm_control_manager_v1.
 */
/**
 * @defgroup iface_hyprland_ctm_control_manager_v1 The hyprland_ctm_control_manager_v1 interface
 *
 * This object is a manager which offers requests to control CTMs.
 *
 * If any changes are done, once this object is destroyed, CTMs are reset back to
 * an identity matrix.
 */
extern const struct wl_interface hyprland_ctm_control_manager_v1_interface;
#endif

#ifndef HYPRLAND_CTM_CONTROL_MANAGER_V1_ERROR_ENUM
#define HYPRLAND_CTM_CONTROL_MANAGER_V1_ERROR_ENUM
enum hyprland_ctm_control_manager_v1_error {
	/**
	 * the matrix values are invalid.
	 */
	HYPRLAND_CTM_CONTROL_MANAGER_V1_ERROR_INVALID_MATRIX = 0,
};
#endif /* HYPRLAND_CTM_CONTROL_MANAGER_V1_ERROR_ENUM */

/**
 * @ingroup iface_hyprland_ctm_control_manager_v1
 * @struct hyprland_ctm_control_manager_v1_listener
 */
struct hyprland_ctm_control_manager_v1_listener {
	/**
	 * the manager is blocked by another CTM manager
	 *
	 * This event is sent if another manager was bound by any client
	 * at the time the current manager was bound. Any
	 * set_ctm_for_output requests from a blocked manager will be
	 * silently ignored by the compositor.
	 *
	 * The client should destroy the manager after receiving this
	 * event.
	 */
	void (*blocked)(void *data,
			struct hyprland_ctm_control_manager_v1 *hyprland_ctm_control_manager_v1);
};

/**
 * @ingroup iface_hyprland_ctm_control_manager_v1
 */
static inline int
hyprland_ctm_control_manager_v1_add_listener(struct hyprland_ctm_control_manager_v1 *hyprland_ctm_control_manager_v1,
					     const struct hyprland_ctm_control_manager_v1_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) hyprland_ctm_control_manager_v1,
				     (void (**)(void)) listener, data);
}

#define HYPRLAND_CTM_CONTROL_MANAGER_V1_SET_CTM_FOR_OUTPUT 0
#define HYPRLAND_CTM_CONTROL_MANAGER_V1_COMMIT 1
#define HYPRLAND_CTM_CONTROL_MANAGER_V1_DESTROY 2

/**
 * @ingroup iface_hyprland_ctm_control_manager_v1
 */
#define HYPRLAND_CTM_CONTROL_MANAGER_V1_BLOCKED_SINCE_VERSION 1

/**
 * @ingroup iface_hyprland_ctm_control_manager_v1
 */
#define HYPRLAND_CTM_CONTROL_MANAGER_V1_SET_CTM_FOR_OUTPUT_SINCE_VERSION 1
/**
 * @ingroup iface_hyprland_ctm_control_manager_v1
 */
#define HYPRLAND_CTM_CONTROL_MANAGER_V1_COMMIT_SINCE_VERSION 1
/**
 * @ingroup iface_hyprland_ctm_control_manager_v1
 */
#define HYPRLAND_CTM_CONTROL_MANAGER_V1_DESTROY_SINCE_VERSION 1

/** @ingroup iface_hyprland_ctm_control_manager_v1 */
static inline void
hyprland_ctm_control_manager_v1_set_user_data(struct hyprland_ctm_control_manager_v1 *hyprland_ctm_control_manager_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) hyprland_ctm_control_manager_v1, user_data);
}

/** @ingroup iface_hyprland_ctm_control_manager_v1 */
static inline void *
hyprland_ctm_control_manager_v1_get_user_data(struct hyprland_ctm_control_manager_v1 *hyprland_ctm_control_manager_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) hyprland_ctm_control_manager_v1);
}

static inline uint32_t
hyprland_ctm_control_manager_v1_get_version(struct hyprland_ctm_control_manager_v1 *hyprland_ctm_control_manager_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) hyprland_ctm_control_manager_v1);
}

/**
 * @ingroup iface_hyprland_ctm_control_manager_v1
 *
 * Set a CTM for a wl_output.
 *
 * This state is not applied immediately; clients must call .commit to
 * apply any pending changes.
 *
 * The provided values describe a 3x3 Row-Major CTM with values in the range of [0, ∞)
 *
 * Passing values outside of the range will raise an invalid_matrix error.
 *
 * The default value of the CTM is an identity matrix.
 *
 * If an output doesn't get a CTM set with set_ctm_for_output and commit is called,
 * that output will get its CTM reset to an identity matrix.
 */
static inline void
hyprland_ctm_control_manager_v1_set_ctm_for_output(struct hyprland_ctm_control_manager_v1 *hyprland_ctm_control_manager_v1, struct wl_output *output, wl_fixed_t mat0, wl_fixed_t mat1, wl_fixed_t mat2, wl_fixed_t mat3, wl_fixed_t mat4, wl_fixed_t mat5, wl_fixed_t mat6, wl_fixed_t mat7, wl_fixed_t mat8)
{
	wl_proxy_marshal_flags((struct wl_proxy *) hyprland_ctm_control_manager_v1,
			 HYPRLAND_CTM_CONTROL_MANAGER_V1_SET_CTM_FOR_OUTPUT, NULL, wl_proxy_get_version((struct wl_proxy *) hyprland_ctm_control_manager_v1), 0, output, mat0, mat1, mat2, mat3, mat4, mat5, mat6, mat7, mat8);
}

/**
 * @ingroup iface_hyprland_ctm_control_manager_v1
 *
 * Commits the pending state(s) set by set_ctm_for_output.
 */
static inline void
hyprland_ctm_control_manager_v1_commit(struct hyprland_ctm_control_manager_v1 *hyprland_ctm_control_manager_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) hyprland_ctm_control_manager_v1,
			 HYPRLAND_CTM_CONTROL_MANAGER_V1_COMMIT, NULL, wl_proxy_get_version((struct wl_proxy *) hyprland_ctm_control_manager_v1), 0);
}

/**
 * @ingroup iface_hyprland_ctm_control_manager_v1
 *
 * All objects created by the manager will still remain valid, until their
 * appropriate destroy request has been called.
 *
 * The CTMs of all outputs will be reset to an identity matrix.
 */
static inline void
hyprland_ctm_control_manager_v1_destroy(struct hyprland_ctm_control_manager_v1 *hyprland_ctm_control_manager_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) hyprland_ctm_control_manager_v1,
			 HYPRLAND_CTM_CONTROL_MANAGER_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) hyprland_ctm_control_manager_v1), WL_MARSHAL_FLAG_DESTROY);
}

#ifdef  __cplusplus
}
#endif

#endif
