words = [
    "attf",
    "csvview",
    "engineeringresumes",
    "esc",
    "gitcommit",
    "keymaps",
    "neovim",
    "noupdate",
    "odoo",
    "prettierd",
    "qweb",
    "rustfmt",
    "saka",
    "stylua",
    "textobject",
    "tmpl",
    "underprepared",
    "uom",
    "xmlformat",
]
